//GLOBAL ACTIONS
export const CHANGE_STATE = "CHANGE_STATE";
export const RESET_STORE = "RESET_STORE";

//LIST PRODUCTS
export const LIST_PRODUCTS = "LIST_PRODUCTS";
export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SET_PRODUCT = "SET_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";

//LIST CATEGORY
export const LIST_CATEGORY = "LIST_CATEGORY";
